create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  email text,
  phone text not null,
  telegram text,
  city text not null,
  delivery_method text not null,
  delivery_price numeric(12, 2) not null default 0,
  street text not null,
  house text not null,
  entrance text,
  floor text,
  apartment_office text,
  comment text,
  total_amount numeric(12, 2) not null default 0,
  total_items integer not null default 0,
  status text not null default 'new',
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.orders add column if not exists telegram text;
alter table public.orders add column if not exists delivery_price numeric(12, 2) not null default 0;
alter table public.orders add column if not exists street text;
alter table public.orders add column if not exists house text;
alter table public.orders add column if not exists entrance text;
alter table public.orders add column if not exists floor text;
alter table public.orders add column if not exists apartment_office text;

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id text,
  product_title text not null,
  product_slug text,
  image_url text,
  price numeric(12, 2) not null default 0,
  size text,
  quantity integer not null default 1,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
