-- Catalog schema for categories and products.
-- Matches the current storefront/admin behavior:
-- - category is optional for a product
-- - product slug is expected to be unique

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.categories add column if not exists name text;
alter table public.categories add column if not exists slug text;
alter table public.categories add column if not exists created_at timestamptz default timezone('utc', now());

update public.categories
set created_at = timezone('utc', now())
where created_at is null;

alter table public.categories
  alter column created_at set default timezone('utc', now());

create unique index if not exists idx_categories_slug_unique
  on public.categories(slug);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null,
  description text,
  price numeric(12, 2) not null,
  old_price numeric(12, 2),
  image_url text,
  sizes jsonb not null default '[]'::jsonb,
  category_id bigint references public.categories(id) on delete set null,
  stock integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.products add column if not exists title text;
alter table public.products add column if not exists slug text;
alter table public.products add column if not exists description text;
alter table public.products add column if not exists price numeric(12, 2);
alter table public.products add column if not exists old_price numeric(12, 2);
alter table public.products add column if not exists image_url text;
alter table public.products add column if not exists sizes jsonb default '[]'::jsonb;
alter table public.products add column if not exists category_id bigint references public.categories(id) on delete set null;
alter table public.products add column if not exists stock integer default 0;
alter table public.products add column if not exists is_active boolean default true;
alter table public.products add column if not exists created_at timestamptz default timezone('utc', now());

do $$
declare
  sizes_type text;
begin
  select c.udt_name
  into sizes_type
  from information_schema.columns as c
  where c.table_schema = 'public'
    and c.table_name = 'products'
    and c.column_name = 'sizes';

  if sizes_type = 'jsonb' then
    execute $sql$
      update public.products
      set sizes = '[]'::jsonb
      where sizes is null
    $sql$;

    execute $sql$
      alter table public.products
        alter column sizes set default '[]'::jsonb,
        alter column sizes set not null
    $sql$;
  elsif sizes_type = '_text' then
    execute $sql$
      update public.products
      set sizes = '{}'::text[]
      where sizes is null
    $sql$;

    execute $sql$
      alter table public.products
        alter column sizes set default '{}'::text[],
        alter column sizes set not null
    $sql$;
  end if;
end $$;

update public.products
set stock = 0
where stock is null;

update public.products
set is_active = true
where is_active is null;

update public.products
set created_at = timezone('utc', now())
where created_at is null;

alter table public.products
  alter column stock set default 0,
  alter column stock set not null,
  alter column is_active set default true,
  alter column is_active set not null,
  alter column created_at set default timezone('utc', now()),
  alter column created_at set not null;

alter table public.products
  alter column category_id drop not null;

create unique index if not exists idx_products_slug_unique
  on public.products(slug);

create index if not exists idx_products_category_id
  on public.products(category_id);

create index if not exists idx_products_is_active
  on public.products(is_active);

create index if not exists idx_products_created_at
  on public.products(created_at desc);
